"""Initial schema with samples table

Revision ID: 254ada664af2
Revises: 
Create Date: 2025-10-27 01:39:27.461725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254ada664af2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_code', sa.String(length=64), nullable=False),
    sa.Column('test_type', sa.String(length=128), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('collected_by', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('received', 'processing', 'completed', 'rejected', name='samplestatus'), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=False),
    sa.Column('sample_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_sample_code'), 'samples', ['sample_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_samples_sample_code'), table_name='samples')
    op.drop_table('samples')
    # ### end Alembic commands ###
